### ISSUE TITLE
Make it clear which tip is likely to save the most time

### ISSUE THREAD

**Issue by mchristofides** [hairybreeches/pgMustard#14]

**Comment by hairybreeches** [comment]
Now, each potential tip is assigned a score, all tips below a certain threshold are discarded, and at most the best three retained. The best tip will be opened by default. 

Hopefully this will reduce false positives and give people a better idea of what to try first. We may well end up doing more on this, or coming back to it to rebalance the scoring, but closing for now until we get more feedback

deployed change at 27/8/19 8:25
